#!/bin/bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

if [[ "$ROOT_DIR" = '' || "$ROOT_DIR" = '/' ]]; then
	exit 1
fi

cd "$ROOT_DIR"

from_commit='HEAD'
to_commit='origin/HEAD'

if [ -n "$1" ]; then
	from_commit="$1"
fi
if [ -n "$2" ]; then
	to_commit="$2"
fi

git fetch
git diff "$from_commit".."$to_commit" --diff-filter=A --name-only | grep 'modifications.*.sql' | sort -t '/' -k 5 | while IFS= read -r modification; do
	printf '# %s\n' "$modification"
	git show "$to_commit":"$modification"
	echo
done

exit 0
